-- Akaar 010: craft taxonomy seed.
--
-- Factual vocabulary only: craft name, region where the craft is practised,
-- and care guidance. No heritage, authenticity or GI claims are seeded, because
-- nothing downstream may present a generated claim as provenance.

insert into public.materials (slug, name_en, name_hi, category) values
  ('cotton','Cotton','Sooti','fibre'),
  ('silk','Silk','Resham','fibre'),
  ('tussar-silk','Tussar silk','Tussar resham','fibre'),
  ('muga-silk','Muga silk','Muga resham','fibre'),
  ('wool','Wool','Oon','fibre'),
  ('pashmina','Pashmina','Pashmina','fibre'),
  ('jute','Jute','Jute','fibre'),
  ('zari','Zari thread','Zari','thread'),
  ('natural-dye','Natural dye','Prakritik rang','dye'),
  ('terracotta-clay','Terracotta clay','Chikni mitti','clay'),
  ('brass','Brass','Peetal','metal'),
  ('bell-metal','Bell metal','Kansa','metal'),
  ('silver','Silver','Chandi','metal'),
  ('sheesham','Sheesham wood','Sheesham lakdi','wood'),
  ('mango-wood','Mango wood','Aam ki lakdi','wood'),
  ('bamboo','Bamboo','Baans','plant'),
  ('cane','Cane','Bent','plant'),
  ('leather','Leather','Chamda','other'),
  ('beads','Beads','Moti','other'),
  ('handmade-paper','Handmade paper','Haath ka kagaz','other')
on conflict (slug) do nothing;

insert into public.techniques (slug, name_en, name_hi, is_handmade, is_handwoven) values
  ('handloom-weaving','Handloom weaving','Handloom bunai', true, true),
  ('pit-loom-weaving','Pit loom weaving','Gaddha kargha bunai', true, true),
  ('hand-embroidery','Hand embroidery','Haath ki kadhai', true, false),
  ('mirror-work','Mirror work','Sheesha kaam', true, false),
  ('tie-dye','Tie and dye','Bandhej', true, false),
  ('block-printing','Hand block printing','Haath ki chhapai', true, false),
  ('hand-painting','Hand painting','Haath ki chitrakari', true, false),
  ('wood-carving','Hand wood carving','Lakdi ki nakkashi', true, false),
  ('lost-wax-casting','Lost-wax casting','Dhokra dhalai', true, false),
  ('metal-inlay','Metal inlay','Dhatu jadai', true, false),
  ('wheel-throwing','Wheel throwing','Chaak par gadhai', true, false),
  ('hand-glazing','Hand glazing','Haath se chamak', true, false),
  ('applique','Applique','Applique', true, false),
  ('crochet','Crochet','Crochet', true, false),
  ('cane-weaving','Cane and bamboo weaving','Baans bunai', true, false)
on conflict (slug) do nothing;

-- Categories
insert into public.crafts (slug, name_en, name_hi, regions) values
  ('textiles','Textiles and weaving','Vastra evam bunai','{}'),
  ('embroidery','Embroidery','Kadhai','{}'),
  ('pottery','Pottery and clay','Mitti ke bartan','{}'),
  ('metalwork','Metal craft','Dhatu shilp','{}'),
  ('woodwork','Wood craft','Kashth shilp','{}'),
  ('painting','Traditional painting','Paramparik chitrakala','{}'),
  ('cane-bamboo','Cane and bamboo','Baans evam bent','{}')
on conflict (slug) do nothing;

-- Crafts, parented to their category
insert into public.crafts (slug, parent_id, name_en, name_hi, regions, care_en, care_hi)
select v.slug, c.id, v.name_en, v.name_hi, v.regions, v.care_en, v.care_hi
from (values
  ('banarasi-weaving','textiles','Banarasi weaving','Banarasi bunai',array['Uttar Pradesh'],
   'Dry clean only. Store wrapped in cotton cloth, away from direct sunlight.',
   'Keval dry clean karein. Sooti kapde mein lapet kar rakhein, dhoop se door.'),
  ('chanderi-weaving','textiles','Chanderi weaving','Chanderi bunai',array['Madhya Pradesh'],
   'Dry clean preferred. Avoid wringing.',
   'Dry clean behtar hai. Nichodein nahin.'),
  ('ikat-weaving','textiles','Ikat weaving','Ikat bunai',array['Telangana','Odisha','Gujarat'],
   'Hand wash separately in cold water for the first few washes.',
   'Pehli kuch dhulai alag se thande paani mein karein.'),
  ('pashmina-weaving','textiles','Pashmina weaving','Pashmina bunai',array['Jammu and Kashmir','Ladakh'],
   'Dry clean only. Store folded with a moth repellent.',
   'Keval dry clean. Mod kar rakhein.'),
  ('bandhani','textiles','Bandhani tie-dye','Bandhani',array['Gujarat','Rajasthan'],
   'Hand wash in cold water. Colour may bleed initially.',
   'Thande paani mein haath se dhoyein. Shuru mein rang chhut sakta hai.'),
  ('ajrakh-printing','textiles','Ajrakh block printing','Ajrakh chhapai',array['Gujarat','Rajasthan'],
   'Hand wash separately. Natural dyes soften with washing.',
   'Alag se haath se dhoyein. Prakritik rang dhulai se halka hota hai.'),
  ('kashidakari','embroidery','Kashidakari embroidery','Kashidakari',array['Rajasthan','Jammu and Kashmir'],
   'Hand wash gently. Do not scrub embroidered areas.',
   'Halke haath se dhoyein. Kadhai wale hisse ko ragdein nahin.'),
  ('chikankari','embroidery','Chikankari embroidery','Chikankari',array['Uttar Pradesh'],
   'Hand wash in mild detergent. Dry in shade.',
   'Halke saabun se haath se dhoyein. Chhaon mein sukhayein.'),
  ('phulkari','embroidery','Phulkari embroidery','Phulkari',array['Punjab','Haryana'],
   'Dry clean recommended for heavily worked pieces.',
   'Adhik kadhai wale kapdon ke liye dry clean behtar hai.'),
  ('kantha','embroidery','Kantha embroidery','Kantha',array['West Bengal','Odisha'],
   'Hand wash in cold water. Dry flat.',
   'Thande paani mein dhoyein. Samtal sukhayein.'),
  ('blue-pottery','pottery','Blue pottery','Neeli mitti ke bartan',array['Rajasthan'],
   'Wipe with a damp cloth. Not dishwasher or microwave safe.',
   'Geele kapde se ponchein. Dishwasher ya microwave mein na rakhein.'),
  ('terracotta','pottery','Terracotta craft','Terracotta shilp',array['West Bengal','Tamil Nadu','Uttar Pradesh'],
   'Keep dry. Dust with a soft brush.',
   'Sookha rakhein. Naram brush se saaf karein.'),
  ('black-pottery','pottery','Black pottery','Kaali mitti ke bartan',array['Manipur','Himachal Pradesh'],
   'Hand wash without detergent. Season before first use.',
   'Bina saabun ke dhoyein. Pehle upyog se pehle taiyar karein.'),
  ('bidriware','metalwork','Bidriware','Bidri',array['Karnataka'],
   'Wipe with a dry cloth. Do not use metal polish.',
   'Sookhe kapde se ponchein. Dhatu polish na lagayein.'),
  ('dhokra','metalwork','Dhokra metal casting','Dhokra',array['Chhattisgarh','West Bengal','Odisha','Jharkhand'],
   'Dust regularly. Avoid abrasive cleaners.',
   'Niyamit dhool hatayein. Ragadne wale cleaner na lagayein.'),
  ('brass-work','metalwork','Brass work','Peetal ka kaam',array['Uttar Pradesh','Gujarat'],
   'Polish occasionally with a brass cleaner. Keep dry.',
   'Kabhi kabhi peetal cleaner se chamkayein. Sookha rakhein.'),
  ('wood-carving','woodwork','Wood carving','Lakdi ki nakkashi',array['Uttar Pradesh','Kerala','Karnataka'],
   'Dust with a dry cloth. Keep away from damp.',
   'Sookhe kapde se dhool hatayein. Nami se door rakhein.'),
  ('channapatna-toys','woodwork','Channapatna lacquered toys','Channapatna khilone',array['Karnataka'],
   'Wipe with a dry cloth. Colours are lacquer based.',
   'Sookhe kapde se ponchein.'),
  ('madhubani','painting','Madhubani painting','Madhubani chitrakala',array['Bihar'],
   'Frame under glass. Keep out of direct sunlight.',
   'Kaanch ke frame mein rakhein. Seedhi dhoop se bachayein.'),
  ('warli','painting','Warli painting','Warli chitrakala',array['Maharashtra'],
   'Keep dry and out of direct sunlight.',
   'Sookha rakhein aur dhoop se bachayein.'),
  ('pattachitra','painting','Pattachitra','Pattachitra',array['Odisha','West Bengal'],
   'Do not roll tightly. Store flat, away from moisture.',
   'Kas kar na lapetein. Samtal rakhein, nami se door.'),
  ('gond-art','painting','Gond painting','Gond chitrakala',array['Madhya Pradesh'],
   'Frame under glass. Avoid humidity.',
   'Kaanch ke frame mein rakhein. Nami se bachayein.'),
  ('kalamkari','painting','Kalamkari','Kalamkari',array['Andhra Pradesh','Telangana'],
   'Hand wash separately in cold water.',
   'Alag se thande paani mein dhoyein.'),
  ('bamboo-craft','cane-bamboo','Bamboo craft','Baans shilp',array['Assam','Tripura','Meghalaya'],
   'Keep dry. Wipe with a damp cloth and dry immediately.',
   'Sookha rakhein. Geele kapde se ponch kar turant sukhayein.'),
  ('cane-furniture','cane-bamboo','Cane furniture','Bent ka furniture',array['Assam','Kerala'],
   'Avoid prolonged damp. Dust regularly.',
   'Lambe samay tak nami se bachayein. Niyamit dhool hatayein.')
) as v(slug, parent_slug, name_en, name_hi, regions, care_en, care_hi)
join public.crafts c on c.slug = v.parent_slug
on conflict (slug) do nothing;
